### ISSUE TITLE
Where to set Cloud VPS ip? 

### ISSUE THREAD

**Issue by jpgtama** [ableli/one-net#1]
Dear ableli, 

one-net is a great idea. I tried to use it but didn't find any place to set my vps ip address in client config.

**Comment by jpgtama** [comment]
I tried to set vps ip to `serverName` and `hostName`, client did connect to server, but when I access my vps ip, it's hovering while I expect to see the web page in my local laptop.

**Comment by ableli** [comment]
Which context type are you using?
tcpContexts or httpContexts.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ableli** [comment]
If you didn’t have a domain name , you’d better config tcpContexts like this.

Please make sure the VPS’s 80 and 9527 ports are not blocking by the VPS vender.



oneNetServer:

      name: firstServer

      oneNetPort: 9527

      tcpContexts:

        -

          contextName: weyong

          internetPort: 80


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jpgtama** [comment]
I didn't well understand `context`. But I want to open my local http service to internet. 
Belows are my config. 


My client applicaton.yml: 

```
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: error
    org.springframework.boot: error
    com.weyong: debug
    io.netty.handler.logging: debug
oneNetClient:
  serverName: xxx.xxx.xxx.xxx
  reconnectAfterNSeconds: 7
  serverConfigs:
    -
      hostName: xxx.xxx.xxx.xxx
      oneNetPort: 9527
      contexts:
        -
          contextName: test1
          localhost: 127.0.0.1
          port: 8080
          localPool: false
```


My server application.yml:
```
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    root: error
    org.springframework.boot: error
    com.weyong: info
    io.netty.handler.logging: debug
oneNetServer:
  name: firstServer
  oneNetPort: 9527
  httpContexts:
    -
      contextName: test1
      zip: true
      aes: false
      kBps: 200
      domainRegExs:
        -
          \w+
```
